[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']

[custom-keybindings/custom0]
binding='<Control><Alt>y'
command='gnome-terminal -- zsh'
name='open zsh'

[custom-keybindings/custom1]
binding='<Shift><Alt>t'
command='bash /home/ap/Documents/obsidian/Ubuntu/.obsidian/custom_scripts/open-tasks'
name='Open obsidian tasks'
